### ISSUE TITLE
Having some trouble with component views (and layouts)

### ISSUE THREAD

**Issue by teppokoivula** [mauricius/WireframeRendererBlade#1]
Hey @mauricius!

I'm posting this issue following a question at the support forum (https://processwire.com/talk/topic/21893-wireframe-wip/?do=findComment&comment=205955). It seems that currently using Blade based component views is a bit tricky, unless I'm missing something:

- In order to make Wireframe detect a Blade based component view, I need to place the [view name].blade.php file to the component's directory (in this case /site/templates/components/Hero/default.blade.php).
- While rendering said view, WireframeRendererBlade modifies the path to point to /site/templates/views/Hero/default.blade.php.
- This means that the original file is never used, and I actually have to a) put a dummy file to /site/templates/components/Hero/default.blade.php (for Wireframe to detect this view) and then put the actual view at /site/templates/views/Hero/default.blade.php (for WireframeRendererBlade).

Ideas? :)

Note that the same thing happens with layouts: normally I would place a layout file at /site/templates/layouts/default.php, but if I add a Blade layout (/site/templates/layouts/default.blade.php), this results in a fatal error since the render method changes the path to /site/templates/views/default.blade.php.

Obviously this won't affect "extends" calls, so if you're extending the layout from the view then you won't run into this issue. That's not how Wireframe layout/view relations work by default, though; normally view doesn't have to know anything about layout, which also makes it possible to switch the layout without modifying any existing views, etc. :)

Please let me know if I misunderstood something! This is the first time I'm using this module, and it's entirely possible that I made a mistake somewhere.

**Comment by mauricius** [comment]
Hey @teppokoivula!

It's totally possible that I missed something when porting over your Twig module to the Blade implementation. I'm currently building a website with WireframeRendererBlade, but I'm strictly using "extends" calls from my views therefore I did not notice your issue.

- Extend a layout
```
@extends('layout::base')
```

- Include a component
```
@component('component::tabs')
...
@endcomponent
```

How can I try to replicate your issue? I have a few ideas of what's wrong, but I would like to know exactly what you're doing because, as I said, I'm using pretty much only the view files to control the output.

**Comment by teppokoivula** [comment]
Right! Looks like our approaches were pretty different :)

In my limited test case I had all my templates in PHP, and then added a single Blade view for a component called "Hero". Now if I render the component in a PHP view file with `Wireframe::component('Hero')`, what happens seems to be that ...

1) the Component class (/site/templates/components/Hero.php) gets initialized (so far so good),
2) my Blade template from /site/templates/components/Hero/default.blade.php is found (as expected), and
3) Wireframe asks WireframeRendererBlade to render the template file — at which point the renderer modifies the path to point to /site/templates/views/Hero/default.blade.php, and since that doesn't exist, an exception is thrown.

The layout issue occurs as soon as I drop a layout file into /site/templates/layouts/default.blade.php: this file never gets loaded, and if I don't have a corresponding file at /site/templates/views/default.blade.php, it'll throw an exception.

I tried to fix this locally by making the WireframeRendererBlade::render() method set the namespace automatically:

```
--- a/WireframeRendererBlade.module.php
+++ b/WireframeRendererBlade.module.php
@@ -87,6 +87,9 @@ class WireframeRendererBlade extends Wire implements Module
         }

         $view = $this->adaptView($view);
+        if ($type != 'view') {
+            $view = $type . '::' . $view;
+        }

         return $this->blade->make($view, $context)->render();
     }
```

This seems to fix the issue in my use case, but could have unexpected side effects and break things at your end :)

**Comment by teppokoivula** [comment]
Just for the record, I'm testing this on Wireframe 0.15.1, i.e. the latest release. There were some component related changes in 0.14.0, and in 0.15.1 I fixed an issue related to renderers and partials. This may be relevant.

**Comment by mauricius** [comment]
Ok, now it makes much more sense. I tested your changes and I agree that this is the way to go. I also tested the updated module in my existing site and it doesn't affect the existing code at all, so I guess this is fine. I already tagged version 0.1.1.

BTW I'm getting an error with Wireframe 0.15.1, you should check it out

`Return value of Wireframe\Config::getPaths() must be an instance of Wireframe\object, instance of stdClass returned` on line 161.

Thanks for your time and for getting back to me!
